---
- name: Baseline IOS hygiene
  cisco.ios.ios_config:
    lines:
      - no ip domain lookup
      - service timestamps log datetime msec
      - service timestamps debug datetime msec
      - line con 0
      - " logging synchronous"
      - " exec-timeout 30 0"
    save_when: modified
