---
- name: SSH management-plane access
  arista.eos.eos_config:
    parents: management ssh
    lines:
      - idle-timeout 15
      - no shutdown
    save_when: modified

- name: Local AAA for login and enable
  arista.eos.eos_config:
    lines:
      - aaa authentication login default local
      - aaa authorization exec default local
    save_when: modified
