---
- name: Password + login hardening
  cisco.ios.ios_config:
    lines:
      - service password-encryption
      - login block-for 60 attempts 3 within 30
      - logging buffered 32768 informational
    save_when: modified
